"""
Finding Provenance Tracker — V2-DESIGN-002 / FIX-012

Tracks the source of every finding in the ledger to distinguish
between tool-sourced (AUTO) and LLM-generated findings.

Auto-sourced findings have full provenance and weight 1.0.
LLM-sourced findings have weight 0.3 until independently verified.
"""

from __future__ import annotations

import hashlib
import logging
import threading
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

_logger = logging.getLogger(__name__)


class FindingSource(str, Enum):
    AUTO = "auto"       # Extracted directly from tool output
    LLM = "llm"        # Generated by LLM reasoning
    VERIFIED = "verified"  # LLM finding confirmed by tool output


@dataclass
class ProvenancedFinding:
    """A finding with source tracking and evidence chain."""
    content: str
    source: FindingSource
    tool_name: str = ""
    timestamp: float = field(default_factory=time.time)
    weight: float = 1.0
    evidence_hash: str = ""
    verified: bool = False
    finding_hash: str = ""

    def __post_init__(self) -> None:
        if not self.finding_hash:
            self.finding_hash = hashlib.sha256(
                self.content.encode(errors="replace")
            ).hexdigest()[:16]
        if self.source == FindingSource.LLM and not self.verified:
            self.weight = 0.3
        elif self.source == FindingSource.AUTO:
            self.weight = 1.0
        elif self.source == FindingSource.VERIFIED:
            self.weight = 1.0


class FindingProvenanceTracker:
    """Thread-safe tracker for finding provenance.

    Maintains a parallel index for O(1) dedup and source queries.
    """

    MAX_FINDINGS = 5000

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._findings: list[ProvenancedFinding] = []
        self._hash_index: set[str] = set()  # O(1) dedup
        self._by_source: dict[FindingSource, list[ProvenancedFinding]] = {
            FindingSource.AUTO: [],
            FindingSource.LLM: [],
            FindingSource.VERIFIED: [],
        }

    def add_finding(
        self,
        content: str,
        source: FindingSource,
        tool_name: str = "",
        evidence_hash: str = "",
    ) -> bool:
        """Add a finding with provenance. Returns True if added (not a duplicate)."""
        finding = ProvenancedFinding(
            content=content,
            source=source,
            tool_name=tool_name,
            evidence_hash=evidence_hash,
        )

        with self._lock:
            if finding.finding_hash in self._hash_index:
                return False  # Duplicate

            if len(self._findings) >= self.MAX_FINDINGS:
                _logger.warning(
                    "Finding provenance tracker at capacity (%d). "
                    "Evicting oldest LLM findings.",
                    self.MAX_FINDINGS,
                )
                self._evict_lowest_weight()

            self._findings.append(finding)
            self._hash_index.add(finding.finding_hash)
            self._by_source[source].append(finding)
            return True

    def verify_finding(self, content: str) -> bool:
        """Mark an LLM finding as verified (promoted to weight 1.0)."""
        finding_hash = hashlib.sha256(
            content.encode(errors="replace")
        ).hexdigest()[:16]

        with self._lock:
            for f in self._findings:
                if f.finding_hash == finding_hash and f.source == FindingSource.LLM:
                    f.source = FindingSource.VERIFIED
                    f.weight = 1.0
                    f.verified = True
                    return True
        return False

    def get_weighted_findings(self, min_weight: float = 0.0) -> list[ProvenancedFinding]:
        """Get findings filtered by minimum weight."""
        with self._lock:
            return [f for f in self._findings if f.weight >= min_weight]

    def get_auto_findings(self) -> list[ProvenancedFinding]:
        """Get only tool-sourced findings (highest confidence)."""
        with self._lock:
            return list(self._by_source[FindingSource.AUTO])

    @property
    def total_count(self) -> int:
        with self._lock:
            return len(self._findings)

    @property
    def auto_count(self) -> int:
        with self._lock:
            return len(self._by_source[FindingSource.AUTO])

    def _evict_lowest_weight(self) -> None:
        """Evict the oldest lowest-weight findings to make room."""
        # Remove up to 100 lowest-weight findings
        to_remove = sorted(
            self._findings,
            key=lambda f: (f.weight, f.timestamp),
        )[:100]
        for f in to_remove:
            self._findings.remove(f)
            self._hash_index.discard(f.finding_hash)
            if f in self._by_source.get(f.source, []):
                self._by_source[f.source].remove(f)
