diff --git a/phantom/interface/cli_app.py b/phantom/interface/cli_app.py
index 41fdeba..9024603 100644
--- a/phantom/interface/cli_app.py
+++ b/phantom/interface/cli_app.py
@@ -15,7 +15,7 @@ import json
 import os
 import sys
 from enum import Enum
-from datetime import UTC, datetime
+from datetime import datetime
 from pathlib import Path
 from typing import Annotated, Optional
 
@@ -28,7 +28,7 @@ from rich.console import Console
 from rich.panel import Panel
 from rich.text import Text
 
-from phantom.interface.tui_design_system import ACTION_BLUE, DANGER_CRIMSON, DANGER_RED, INFO_BLUE, INFO_ROYAL, NEUTRAL_DARK, WARNING_AMBER, WARNING_ORANGE, SUCCESS_GREEN
+from phantom.interface.tui_design_system import ACTION_BLUE, DANGER_CRIMSON, DANGER_RED, INFO_BLUE, NEUTRAL_DARK, WARNING_AMBER, WARNING_ORANGE, SUCCESS_GREEN
 
 console = Console()
 
@@ -367,7 +367,7 @@ def scan(
     )
 
     # Delegate to existing main logic
-    from phantom.config import Config, apply_saved_config, save_current_config
+    from phantom.config import Config, apply_saved_config
     from phantom.interface.main import (
         apply_config_override,
         check_docker_installed,
@@ -605,7 +605,7 @@ def resume(
     import argparse
 
     from pathlib import Path
-    from phantom.checkpoint.checkpoint import CheckpointManager, CHECKPOINT_INTERVAL
+    from phantom.checkpoint.checkpoint import CheckpointManager
 
     # Resolve numeric ID (e.g. "2") to an actual run name.
     resolved = _resolve_run_name(run_name)
@@ -1037,7 +1037,7 @@ def _render_html_report(run_name: str, data: dict) -> str:
   <div class="sev-card" style="background:{ACTION_BLUE}22;border:1px solid {ACTION_BLUE}"><div style="font-size:2rem;font-weight:700;color:{ACTION_BLUE}">{counts["info"]}</div>Info</div>
 </div>
 <h2>Findings ({len(vulns_sorted)})</h2>
-{"".join(["<p><em>No vulnerabilities found.</em></p>"]) if not vulns_sorted else vuln_rows}
+{"<p><em>No vulnerabilities found.</em></p>" if not vulns_sorted else vuln_rows}
 <footer>Generated by <strong>Phantom</strong> ΓÇö Autonomous Adversary Simulation Platform | <a href="https://github.com/Usta0x001/Phantom" style="color:{DANGER_CRIMSON}">github.com/Usta0x001/Phantom</a></footer>
 </body>
 </html>"""
