diff --git a/phantom/tools/reporting/elite_reporting.py b/phantom/tools/reporting/elite_reporting.py
index d7ff52a..73c526e 100644
--- a/phantom/tools/reporting/elite_reporting.py
+++ b/phantom/tools/reporting/elite_reporting.py
@@ -383,298 +383,8 @@ def _generate_remediation_timeline(severity: str, complexity: str) -> str:
     return timeline_map.get((severity, complexity), "30 days")
 
 
-@register_tool(sandbox_execution=False)
-def create_elite_report(
-    title: str,
-    severity: str,
-    confidence: str,
-    vuln_class: str,
-    target: str,
-    technical_details: str,
-    remediation: str,
-    poc_code: str | None = None,
-    cve_id: str | None = None,
-    cwe_id: str | None = None,
-    cvss_score: float | None = None,
-    successful_payloads: list[str] | None = None,
-    hypothesis_id: str | None = None,
-    hypothesis_ledger: Any = None,
-    screenshots: list[dict[str, str]] | None = None,
-    remediation_complexity: str = "MEDIUM"
-) -> dict[str, Any]:
-    """
-    Create an elite penetration testing report with OWASP/CWE compliance mapping.
-    
-    This function transforms basic vulnerability data into a professional deliverable with:
-    - OWASP Top 10 2021 mapping
-    - CWE Top 25 mapping
-    - Executive summary (non-technical)
-    - Business impact analysis
-    - Attack chain reconstruction (from hypothesis ledger)
-    - Screenshot evidence collection
-    - Remediation timeline recommendations
-    
-    Args:
-        title: Vulnerability title
-        severity: CRITICAL, HIGH, MEDIUM, LOW
-        confidence: VERIFIED, LIKELY, SUSPECTED
-        vuln_class: Phantom vulnerability class (e.g., 'sqli', 'xss', 'rce')
-        target: Target URL or system
-        technical_details: Technical analysis and exploitation details
-        remediation: Remediation recommendations
-        poc_code: Proof-of-concept code (optional)
-        cve_id: Associated CVE identifier (optional)
-        cwe_id: CWE identifier (optional, auto-mapped if not provided)
-        cvss_score: CVSS 3.1 base score (optional)
-        successful_payloads: List of successful exploit payloads (optional)
-        hypothesis_id: Hypothesis ID for attack chain reconstruction (optional)
-        hypothesis_ledger: HypothesisLedger instance for reading attack history (optional)
-        screenshots: List of screenshot dictionaries with 'path' and 'description' keys
-        remediation_complexity: LOW, MEDIUM, HIGH (affects timeline)
-        
-    Returns:
-        {
-            "status": "success",
-            "report": {
-                "title": "SQL Injection in Login Form",
-                "severity": "CRITICAL",
-                "compliance": {
-                    "owasp_category": "A03:2021",
-                    "owasp_name": "Injection",
-                    "cwe_id": "CWE-89",
-                    "cwe_name": "SQL Injection",
-                    "cwe_rank": 3,
-                    "sans_top_25": true
-                },
-                "executive_summary": "A critical-severity SQL Injection...",
-                "business_impact": "- Data Breach Risk: ...",
-                "attack_chain": [
-                    {"step": 1, "action": "Sent SQLi payload", "payload": "' OR '1'='1", ...}
-                ],
-                "remediation_timeline": "Immediately (within 24 hours)",
-                ...
-            },
-            "export_formats": {
-                "json": "/path/to/report.json",
-                "html": "/path/to/report.html",
-                "markdown": "/path/to/report.md"
-            }
-        }
-    
-    Example:
-        >>> result = create_elite_report(
-        ...     title="SQL Injection in Login Form",
-        ...     severity="CRITICAL",
-        ...     confidence="VERIFIED",
-        ...     vuln_class="sqli",
-        ...     target="https://example.com/login",
-        ...     technical_details="Injected ' OR '1'='1 in username field...",
-        ...     remediation="Use parameterized queries",
-        ...     poc_code="curl -X POST https://example.com/login -d \"username=' OR '1'='1\"",
-        ...     successful_payloads=["' OR '1'='1", "admin' --"]
-        ... )
-    """
-    try:
-        logger.info(f"[P8] Creating elite report for: {title}")
-        
-        # Map to compliance frameworks
-        owasp_category, owasp_name = _map_vuln_to_owasp(vuln_class)
-        mapped_cwe_id, cwe_name, cwe_rank = _map_vuln_to_cwe(vuln_class, cwe_id)
-        
-        # Override with provided CWE if available
-        if cwe_id and not cwe_name:
-            cwe_name = CWE_TOP_25_MAP.get(cwe_id, {}).get("name")
-            cwe_rank = CWE_TOP_25_MAP.get(cwe_id, {}).get("rank")
-        elif not cwe_id:
-            cwe_id = mapped_cwe_id
-        
-        compliance = ComplianceMapping(
-            owasp_category=owasp_category,
-            owasp_name=owasp_name,
-            cwe_id=cwe_id,
-            cwe_name=cwe_name,
-            cwe_rank=cwe_rank,
-            sans_top_25=(cwe_rank is not None and cwe_rank <= 25),
-            cvss_score=cvss_score,
-            severity=severity
-        )
-        
-        # Generate executive summary
-        executive_summary = _generate_executive_summary(
-            title=title,
-            severity=severity,
-            vuln_class=vuln_class,
-            target=target,
-            confidence=confidence,
-            owasp_name=owasp_name
-        )
-        
-        # Generate business impact
-        business_impact = _generate_business_impact(severity, vuln_class)
-        
-        # Reconstruct attack chain from hypothesis ledger
-        attack_chain: list[AttackChainStep] = []
-        if hypothesis_id and hypothesis_ledger:
-            try:
-                hyp = hypothesis_ledger._hypotheses.get(hypothesis_id)
-                if hyp:
-                    for idx, payload in enumerate(hyp.payloads_tested, 1):
-                        # Check if this payload was successful
-                        is_successful = payload in (hyp.successful_payloads if hasattr(hyp, "successful_payloads") else [])
-                        
-                        step = AttackChainStep(
-                            step_number=idx,
-                            action=f"Tested {vuln_class} payload #{idx}",
-                            payload=payload,
-                            response="Exploitation successful" if is_successful else "No vulnerability detected"
-                        )
-                        attack_chain.append(step)
-                        
-                        # Stop at first successful payload for cleaner narrative
-                        if is_successful and len(attack_chain) >= 5:
-                            break
-            except Exception as e:
-                logger.warning(f"[P8] Failed to reconstruct attack chain: {e}")
-        
-        # Generate remediation timeline
-        remediation_timeline = _generate_remediation_timeline(severity, remediation_complexity)
-        
-        # Create elite report
-        report = EliteReport(
-            title=title,
-            severity=severity,
-            confidence=confidence,
-            vuln_class=vuln_class,
-            compliance=compliance,
-            attack_chain=attack_chain,
-            executive_summary=executive_summary,
-            technical_details=technical_details,
-            business_impact=business_impact,
-            screenshots=screenshots or [],
-            poc_code=poc_code or "",
-            successful_payloads=successful_payloads or [],
-            remediation=remediation,
-            remediation_complexity=remediation_complexity,
-            remediation_timeline=remediation_timeline,
-            target=target,
-            cve_id=cve_id
-        )
-        
-        logger.info(f"[P8] Elite report created: {title} mapped to {owasp_category or 'N/A'}")
-        
-        return {
-            "status": "success",
-            "report": report.to_dict(),
-            "summary": f"Elite report created for {title} ({severity} severity, {owasp_category or 'unmapped'})",
-            "compliance_summary": f"{owasp_category or 'N/A'}: {owasp_name or 'N/A'}, {cwe_id or 'N/A'}: {cwe_name or 'N/A'}",
-            "metadata": {
-                "owasp_mapped": owasp_category is not None,
-                "cwe_mapped": cwe_id is not None,
-                "sans_top_25": compliance.sans_top_25,
-                "attack_chain_steps": len(attack_chain),
-                "screenshots": len(screenshots or []),
-                "timestamp": datetime.now(UTC).isoformat()
-            }
-        }
-    
-    except Exception as e:
-        logger.error(f"[P8] Failed to create elite report: {e}", exc_info=True)
-        return {
-            "status": "error",
-            "error": str(e),
-            "summary": f"Failed to create elite report: {e}"
-        }
 
 
-@register_tool(sandbox_execution=False)
-def export_elite_report(
-    report: dict[str, Any],
-    output_dir: str,
-    formats: list[str] | None = None
-) -> dict[str, Any]:
-    """
-    Export elite report to multiple formats (JSON, HTML, Markdown, CSV).
-    
-    Args:
-        report: Elite report dictionary from create_elite_report()
-        output_dir: Output directory for exported files
-        formats: List of formats to export (default: ["json", "markdown", "html"])
-                Valid formats: "json", "markdown", "html", "csv"
-    
-    Returns:
-        {
-            "status": "success",
-            "exported_files": {
-                "json": "/path/to/report.json",
-                "markdown": "/path/to/report.md",
-                "html": "/path/to/report.html"
-            }
-        }
-    """
-    try:
-        if formats is None:
-            formats = ["json", "markdown", "html"]
-        
-        output_path = Path(output_dir)
-        output_path.mkdir(parents=True, exist_ok=True)
-        
-        # Sanitize title for filename
-        title = report.get("title", "vulnerability_report")
-        safe_title = re.sub(r'[^\w\s-]', '', title).strip().replace(' ', '_')
-        timestamp = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
-        base_filename = f"{safe_title}_{timestamp}"
-        
-        exported_files = {}
-        
-        # Export JSON
-        if "json" in formats:
-            json_path = output_path / f"{base_filename}.json"
-            with open(json_path, 'w', encoding='utf-8') as f:
-                json.dump(report, f, indent=2, ensure_ascii=False)
-            exported_files["json"] = str(json_path)
-            logger.info(f"[P8] Exported JSON report to {json_path}")
-        
-        # Export Markdown
-        if "markdown" in formats:
-            md_path = output_path / f"{base_filename}.md"
-            markdown_content = _generate_markdown_report(report)
-            with open(md_path, 'w', encoding='utf-8') as f:
-                f.write(markdown_content)
-            exported_files["markdown"] = str(md_path)
-            logger.info(f"[P8] Exported Markdown report to {md_path}")
-        
-        # Export HTML
-        if "html" in formats:
-            html_path = output_path / f"{base_filename}.html"
-            html_content = _generate_html_report(report)
-            with open(html_path, 'w', encoding='utf-8') as f:
-                f.write(html_content)
-            exported_files["html"] = str(html_path)
-            logger.info(f"[P8] Exported HTML report to {html_path}")
-        
-        # Export CSV (findings summary)
-        if "csv" in formats:
-            csv_path = output_path / f"{base_filename}.csv"
-            csv_content = _generate_csv_report(report)
-            with open(csv_path, 'w', encoding='utf-8') as f:
-                f.write(csv_content)
-            exported_files["csv"] = str(csv_path)
-            logger.info(f"[P8] Exported CSV report to {csv_path}")
-        
-        return {
-            "status": "success",
-            "exported_files": exported_files,
-            "summary": f"Exported {len(exported_files)} report format(s)",
-            "formats": list(exported_files.keys())
-        }
-    
-    except Exception as e:
-        logger.error(f"[P8] Failed to export report: {e}", exc_info=True)
-        return {
-            "status": "error",
-            "error": str(e),
-            "exported_files": {}
-        }
 
 
 def _generate_markdown_report(report: dict[str, Any]) -> str:
