diff --git a/phantom/tools/vuln_intel/cve_auto_integration.py b/phantom/tools/vuln_intel/cve_auto_integration.py
index 5512c52..36abbc2 100644
--- a/phantom/tools/vuln_intel/cve_auto_integration.py
+++ b/phantom/tools/vuln_intel/cve_auto_integration.py
@@ -334,281 +334,6 @@ def _generate_recommended_payloads(
     return payloads
 
 
-@register_tool(sandbox_execution=False)
-def auto_queue_cve_exploits(
-    tech_stack: dict[str, Any],
-    base_url: str,
-    hypothesis_ledger: Any = None,
-    min_severity: str = "MEDIUM",
-    prioritize_exploits: bool = True,
-    max_hypotheses: int = 20
-) -> dict[str, Any]:
-    """
-    Automatically queue CVE-based exploitation hypotheses from fingerprinted tech stack.
-    
-    This is the MAIN FUNCTION that bridges tech detection ΓåÆ CVE lookup ΓåÆ hypothesis queueing.
-    
-    WORKFLOW:
-    1. Parse tech_stack dictionary for products with versions
-    2. Call version_to_cves() for each technology
-    3. Map CVEs to vulnerability classes
-    4. Generate attack surfaces based on product/CVE
-    5. Queue hypotheses in hypothesis ledger
-    6. Return prioritized exploitation plan
-    
-    Args:
-        tech_stack: Tech stack dictionary from identify_tech_stack()
-                   Format: {
-                       "web_servers": [{"name": "Apache", "version": "2.4.49", "confidence": "high"}],
-                       "languages": [{"name": "PHP", "version": "7.4.3"}],
-                       "frameworks": [...],
-                       ...
-                   }
-        base_url: Target base URL (e.g., "https://example.com")
-        hypothesis_ledger: HypothesisLedger instance (optional, for direct integration)
-        min_severity: Minimum CVE severity to queue (CRITICAL, HIGH, MEDIUM, LOW)
-        prioritize_exploits: If True, prioritize CVEs with available exploits
-        max_hypotheses: Maximum number of hypotheses to queue (prevents flooding)
-        
-    Returns:
-        {
-            "hypotheses_queued": 5,
-            "cves_found": 12,
-            "exploitation_plan": [
-                {
-                    "priority": 1,
-                    "cve_id": "CVE-2021-41773",
-                    "product": "Apache",
-                    "severity": "CRITICAL",
-                    "hypothesis_id": "H-0042",
-                    "attack_surface": "https://example.com/cgi-bin/.%2e/.%2e/etc/passwd",
-                    "exploit_available": true,
-                    "recommended_action": "Test path traversal payloads immediately"
-                },
-                ...
-            ],
-            "summary": "Queued 5 high-priority CVE exploits for Apache/2.4.49",
-            "status": "success"
-        }
-    
-    Example:
-        >>> tech_stack = {
-        ...     "web_servers": [{"name": "Apache", "version": "2.4.49", "confidence": "high"}]
-        ... }
-        >>> result = auto_queue_cve_exploits(tech_stack, "https://example.com")
-        >>> print(result["hypotheses_queued"])  # 3
-    """
-    try:
-        # Import here to avoid circular dependencies
-        from phantom.tools.vuln_intel.vuln_intel_actions import version_to_cves
-        from phantom.tools.hypothesis.hypothesis_actions import add_hypothesis
-        
-        logger.info(f"[P7] Starting CVE auto-integration for {base_url}")
-        
-        # Severity ranking for filtering
-        severity_rank = {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1, "INFO": 0}
-        min_severity_rank = severity_rank.get(min_severity.upper(), 2)
-        
-        all_hypotheses: list[CVEExploitHypothesis] = []
-        cves_found = 0
-        
-        # Extract technologies with versions
-        technologies = []
-        for category in ["web_servers", "languages", "frameworks", "cms", "databases"]:
-            if category in tech_stack:
-                for tech in tech_stack[category]:
-                    if isinstance(tech, dict) and "version" in tech and tech["version"]:
-                        technologies.append({
-                            "name": tech["name"],
-                            "version": tech["version"],
-                            "category": category
-                        })
-        
-        logger.info(f"[P7] Found {len(technologies)} technologies with versions")
-        
-        # Query CVEs for each technology
-        for tech in technologies:
-            version_string = f"{tech['name']}/{tech['version']}"
-            logger.info(f"[P7] Querying CVEs for {version_string}")
-            
-            try:
-                cve_result = version_to_cves(
-                    version_string=version_string,
-                    include_exploits=True
-                )
-                
-                if cve_result.get("status") != "success":
-                    logger.warning(f"[P7] CVE lookup failed for {version_string}")
-                    continue
-                
-                cves = cve_result.get("cves", [])
-                cves_found += len(cves)
-                logger.info(f"[P7] Found {len(cves)} CVEs for {version_string}")
-                
-                # Process each CVE
-                for cve in cves:
-                    # Filter by severity
-                    cve_severity = cve.get("severity", "MEDIUM").upper()
-                    if severity_rank.get(cve_severity, 0) < min_severity_rank:
-                        continue
-                    
-                    # Map to vulnerability class
-                    description = cve.get("description", "")
-                    vuln_class = _map_cve_to_vuln_class(description)
-                    
-                    # Check for exploits
-                    exploits = cve.get("exploits", [])
-                    exploit_available = len(exploits) > 0
-                    exploit_type = None
-                    exploit_url = None
-                    
-                    if exploit_available:
-                        # Prioritize Metasploit exploits
-                        metasploit = [e for e in exploits if "metasploit" in e.get("type", "").lower()]
-                        if metasploit:
-                            exploit_type = "metasploit"
-                            exploit_url = metasploit[0].get("url")
-                        else:
-                            exploit_type = "poc"
-                            exploit_url = exploits[0].get("url")
-                    
-                    # Generate attack surfaces
-                    attack_surfaces = _generate_attack_surfaces(
-                        product=tech["name"],
-                        version=tech["version"],
-                        base_url=base_url,
-                        vuln_class=vuln_class
-                    )
-                    
-                    # Generate recommended payloads
-                    recommended_payloads = _generate_recommended_payloads(
-                        vuln_class=vuln_class,
-                        product=tech["name"],
-                        cve_description=description
-                    )
-                    
-                    # Create hypothesis for each attack surface
-                    for surface in attack_surfaces[:3]:  # Limit to 3 surfaces per CVE
-                        hypothesis = CVEExploitHypothesis(
-                            cve_id=cve.get("cve_id", ""),
-                            product=tech["name"],
-                            version=tech["version"],
-                            severity=cve_severity,
-                            description=description,
-                            vuln_class=vuln_class,
-                            attack_surface=surface,
-                            exploit_available=exploit_available,
-                            exploit_type=exploit_type,
-                            exploit_url=exploit_url,
-                            cvss_score=cve.get("cvss_score"),
-                            confidence="HIGH" if exploit_available else "MEDIUM",
-                            recommended_payloads=recommended_payloads,
-                            metadata={
-                                "category": tech["category"],
-                                "cve_data": cve,
-                                "queued_at": datetime.now(UTC).isoformat()
-                            }
-                        )
-                        all_hypotheses.append(hypothesis)
-            
-            except Exception as e:
-                logger.error(f"[P7] Error processing CVEs for {version_string}: {e}")
-                continue
-        
-        # Prioritize hypotheses
-        def priority_score(h: CVEExploitHypothesis) -> tuple:
-            """Calculate priority score (higher is better)."""
-            severity_score = severity_rank.get(h.severity, 0)
-            exploit_score = 10 if h.exploit_available else 0
-            metasploit_bonus = 5 if h.exploit_type == "metasploit" else 0
-            return (severity_score, exploit_score + metasploit_bonus, h.cvss_score or 0)
-        
-        all_hypotheses.sort(key=priority_score, reverse=True)
-        
-        # Queue top hypotheses
-        exploitation_plan = []
-        hypotheses_queued = 0
-        
-        for idx, hypothesis in enumerate(all_hypotheses[:max_hypotheses], 1):
-            # Queue in hypothesis ledger if provided
-            hypothesis_id = None
-            if hypothesis_ledger:
-                try:
-                    hypothesis_id = hypothesis_ledger.add(
-                        surface=hypothesis.attack_surface,
-                        vuln_class=hypothesis.vuln_class
-                    )
-                    logger.info(f"[P7] Queued hypothesis {hypothesis_id}: {hypothesis.cve_id}")
-                except Exception as e:
-                    logger.error(f"[P7] Failed to queue hypothesis: {e}")
-            else:
-                # Fallback to add_hypothesis tool
-                try:
-                    hyp_result = add_hypothesis(
-                        surface=hypothesis.attack_surface,
-                        vuln_class=hypothesis.vuln_class
-                    )
-                    hypothesis_id = hyp_result.get("hypothesis_id")
-                except Exception as e:
-                    logger.error(f"[P7] Failed to call add_hypothesis: {e}")
-            
-            hypotheses_queued += 1
-            
-            # Build exploitation plan entry
-            plan_entry = {
-                "priority": idx,
-                "cve_id": hypothesis.cve_id,
-                "product": f"{hypothesis.product}/{hypothesis.version}",
-                "severity": hypothesis.severity,
-                "vuln_class": hypothesis.vuln_class,
-                "hypothesis_id": hypothesis_id,
-                "attack_surface": hypothesis.attack_surface,
-                "exploit_available": hypothesis.exploit_available,
-                "exploit_type": hypothesis.exploit_type,
-                "exploit_url": hypothesis.exploit_url,
-                "confidence": hypothesis.confidence,
-                "recommended_payloads": hypothesis.recommended_payloads[:3],  # Top 3
-                "recommended_action": _generate_action(hypothesis)
-            }
-            exploitation_plan.append(plan_entry)
-        
-        # Generate summary
-        if hypotheses_queued == 0:
-            summary = f"No CVEs found matching minimum severity {min_severity}"
-            status = "no_cves_found"
-        else:
-            critical_count = sum(1 for h in all_hypotheses[:max_hypotheses] if h.severity == "CRITICAL")
-            high_count = sum(1 for h in all_hypotheses[:max_hypotheses] if h.severity == "HIGH")
-            summary = f"Queued {hypotheses_queued} CVE exploits: {critical_count} CRITICAL, {high_count} HIGH"
-            status = "success"
-        
-        result = {
-            "hypotheses_queued": hypotheses_queued,
-            "cves_found": cves_found,
-            "exploitation_plan": exploitation_plan,
-            "summary": summary,
-            "status": status,
-            "metadata": {
-                "technologies_scanned": len(technologies),
-                "min_severity": min_severity,
-                "prioritize_exploits": prioritize_exploits,
-                "timestamp": datetime.now(UTC).isoformat()
-            }
-        }
-        
-        logger.info(f"[P7] CVE auto-integration complete: {summary}")
-        return result
-    
-    except Exception as e:
-        logger.error(f"[P7] CVE auto-integration failed: {e}", exc_info=True)
-        return {
-            "hypotheses_queued": 0,
-            "cves_found": 0,
-            "exploitation_plan": [],
-            "summary": f"CVE auto-integration failed: {str(e)}",
-            "status": "error",
-            "error": str(e)
-        }
 
 
 def _generate_action(hypothesis: CVEExploitHypothesis) -> str:
@@ -622,144 +347,5 @@ def _generate_action(hypothesis: CVEExploitHypothesis) -> str:
         return f"Manual testing required for {hypothesis.vuln_class} - Review CVE {hypothesis.cve_id}"
 
 
-@register_tool(sandbox_execution=False)
-def enrich_hypothesis_with_cve(
-    hypothesis_id: str,
-    cve_id: str,
-    hypothesis_ledger: Any = None
-) -> dict[str, Any]:
-    """
-    Enrich an existing hypothesis with CVE metadata.
-    
-    Useful when CVEs are discovered AFTER hypothesis creation.
-    
-    Args:
-        hypothesis_id: Hypothesis ID (e.g., "H-0042")
-        cve_id: CVE identifier (e.g., "CVE-2021-41773")
-        hypothesis_ledger: HypothesisLedger instance
-        
-    Returns:
-        {
-            "status": "success",
-            "hypothesis_id": "H-0042",
-            "cve_id": "CVE-2021-41773",
-            "enriched_data": {...}
-        }
-    """
-    try:
-        from phantom.tools.vuln_intel.vuln_intel_actions import get_cve_details
-        
-        logger.info(f"[P7] Enriching hypothesis {hypothesis_id} with CVE {cve_id}")
-        
-        # Fetch CVE details
-        cve_data = get_cve_details(cve_id=cve_id)
-        
-        if cve_data.get("status") != "success":
-            return {
-                "status": "error",
-                "hypothesis_id": hypothesis_id,
-                "cve_id": cve_id,
-                "error": "Failed to fetch CVE details"
-            }
-        
-        # Update hypothesis metadata (if ledger provided)
-        if hypothesis_ledger:
-            try:
-                hyp = hypothesis_ledger._hypotheses.get(hypothesis_id)
-                if hyp:
-                    # Store CVE data in hypothesis
-                    if not hasattr(hyp, "metadata"):
-                        hyp.metadata = {}
-                    hyp.metadata["cve_id"] = cve_id
-                    hyp.metadata["cve_data"] = cve_data.get("cve_details", {})
-                    hyp.metadata["enriched_at"] = datetime.now(UTC).isoformat()
-            except Exception as e:
-                logger.warning(f"[P7] Could not update hypothesis ledger: {e}")
-        
-        return {
-            "status": "success",
-            "hypothesis_id": hypothesis_id,
-            "cve_id": cve_id,
-            "enriched_data": cve_data.get("cve_details", {}),
-            "summary": f"Hypothesis {hypothesis_id} enriched with {cve_id}"
-        }
-    
-    except Exception as e:
-        logger.error(f"[P7] Failed to enrich hypothesis: {e}")
-        return {
-            "status": "error",
-            "hypothesis_id": hypothesis_id,
-            "cve_id": cve_id,
-            "error": str(e)
-        }
 
 
-@register_tool(sandbox_execution=False)
-def get_cve_exploitation_status(
-    cve_id: str,
-    hypothesis_ledger: Any = None
-) -> dict[str, Any]:
-    """
-    Check if a CVE has been tested and get exploitation status.
-    
-    Args:
-        cve_id: CVE identifier
-        hypothesis_ledger: HypothesisLedger instance
-        
-    Returns:
-        {
-            "cve_id": "CVE-2021-41773",
-            "tested": true,
-            "confirmed": true,
-            "hypotheses": ["H-0042", "H-0043"],
-            "status": "EXPLOITABLE"
-        }
-    """
-    try:
-        if not hypothesis_ledger:
-            return {
-                "cve_id": cve_id,
-                "tested": False,
-                "status": "UNKNOWN",
-                "message": "No hypothesis ledger provided"
-            }
-        
-        # Search for hypotheses with this CVE
-        matching_hypotheses = []
-        confirmed = False
-        
-        for hyp in hypothesis_ledger._hypotheses.values():
-            metadata = getattr(hyp, "metadata", {})
-            if metadata.get("cve_id") == cve_id:
-                matching_hypotheses.append(hyp.id)
-                if hyp.status == "confirmed":
-                    confirmed = True
-        
-        if not matching_hypotheses:
-            return {
-                "cve_id": cve_id,
-                "tested": False,
-                "confirmed": False,
-                "status": "NOT_TESTED",
-                "hypotheses": []
-            }
-        
-        status = "EXPLOITABLE" if confirmed else "TESTING_IN_PROGRESS"
-        
-        return {
-            "cve_id": cve_id,
-            "tested": True,
-            "confirmed": confirmed,
-            "hypotheses": matching_hypotheses,
-            "status": status,
-            "summary": f"{cve_id} is {status.lower().replace('_', ' ')}"
-        }
-    
-    except Exception as e:
-        logger.error(f"[P7] Failed to get CVE status: {e}")
-        return {
-            "cve_id": cve_id,
-            "tested": False,
-            "status": "ERROR",
-            "error": str(e)
-        }
